name: flutter_auth
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.6
  flutter_linkify: ^6.0.0
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  cupertino_icons: ^1.0.3
  firebase_auth: ^4.6.3
  google_fonts: ^4.0.4
  flutter_svg: ^2.0.5
  fl_chart: ^0.62.0
  provider: ^6.0.5
  intl: ^0.17.0
  universal_html: ^2.2.4
  firebase_messaging: ^14.8.0
  flutter_image_slideshow: ^0.1.6
  cached_network_image: ^3.2.0
  image_picker_web: ^3.1.1
  file_picker: ^8.0.3
  image_picker: ^0.8.4+4
  firebase_storage: ^11.2.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  email_validator: ^2.0.1
  flutter_lints: ^3.0.2
    
flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
 